### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by FenekAlfa** [bemusic/bemuse#185] opened 2015-05-11 06:11 UTC
[http://i.imgur.com/TydSQpV.png]
If dark mode isn't a thing, then the game is not loading the UI.
If dark mode is a thing, then it's toggling on it's own and not turning off. Either way a bug.

Linux Mint 17.1
Firefox 37.0.2

**Comment by dtinth** [comment] 2015-05-11 11:02
Thanks for the report. Is it always reproducible? Does it only happen with Firefox or it happens in Chrome/Chromium as well?




This seems more like a browser bug or a network issue.

**Comment by FenekAlfa** [comment] 2015-05-12 08:49
It's reproducible but it can happen after different amount of songs. I don't have Chromium, so I'll try later.

**Comment by dtinth** [comment] 2015-09-03 02:09
I’d recommend using Blink-based browsers instead, because it has better timing and more support for new standards (e.g. service workers), and that helps making the skin load more reliably. In addition, I upgraded Pixi.js to v3, so it may have helped.

Closing this for now.

**Closed by dtinth** 2015-09-03 02:09 UTC
